---
- hosts: localhost
  gather_facts: False
  roles:
    - { role: Azure.azure_modules }
  vars_files:
    - azure_vars.yml
  tasks:
   - name: Create Azure SMS
     azure_rm_deployment:
       state: present
       resource_group_name: "{{ ResourceGroup }}"
       template_link: 'https://raw.githubusercontent.com/cadgo/CHKP/master/azure/SMS.json'
       parameters:
         location:
           value: "{{ TmLocation }}"
         vmName:
           value: "{{ SMSName }}"
         adminPassword:
           value: "{{ Password }}"
         Subnet1StartAddress:
           value: 10.0.1.11
         vnetNewOrExisting:
           value: existing
         virtualNetworkExistingRGName:
           value: "{{ ResourceGroup }}"
         
