---
- hosts: localhost
  gather_facts: False
  roles:
    - { role: Azure.azure_modules }
  vars_files:
    - azure_vars.yml
  tasks:
   - name: Create FW Azure Deploy
     azure_rm_deployment:
       state: present
       resource_group_name: "{{ ResourceGroup }}"
       template_link: 'https://raw.githubusercontent.com/cadgo/CHKP/master/azure/CheckPointFirewall.json'
       parameters:
         location:
           value: "{{ TmLocation }}"
         vmName:
           value: "{{ GwName }}"
         adminPassword:
           value: "{{ Password }}"
         sicKey:
           value: "{{ sickey }}"
         virtualNetworkName:
           value: "{{ NetName }}"
         virtualNetworkAddressPrefix:
           value: "{{ NetPref  }}"
         Subnet1Prefix:
           value: "{{ Sub1Pref }}"
         Subnet2Prefix:
           value: "{{ Sub2Pref }}" 
         Subnet1StartAddress:
           value: "{{ IPFront }}"
         Subnet2StartAddress:
           value: "{{ IPBack }}"

    # - name: Create Azure Deploy
    #   azure_rm_deployment:
    #     resource_group: "grp1"
    #     state: present
    #     location: "eastus"
    #     template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
    #     deployment_name: "hola"
    #     parameters:
    #       adminUsername:
    #         value: chouseknecht
    #       adminPassword:
    #         value: password123!
    #       ubuntuOSVersion:
    #         value: "16.04.0-LTS"
    #   register: output
         
