---
- hosts: localhost
  gather_facts: False
  vars_files:
    - azure_vars.yml
  tasks:
   - name: Create Azure Deploy
     azure_rm_deployment:
       state: present
       resource_group_name: "{{ CheckPointGw | default('CheckPointGw', true) }}"
       template_link: 'https://raw.githubusercontent.com/cadgo/CHKP/master/azure/CheckPointFirewall.json'
       parameters:
         location:
           value: East US
         vmName:
           value: "{{ GwName }}"
         adminPassword:
           value: "{{ Password }}"
         sicKey:
           value: "{{ sickey }}"
         
