---
- hosts: localhost
  gather_facts: False
  vars_files:
    - azure_vars.yml
  tasks:
   - name: Create Azure Deploy
     azure_rm_deployment:
       state: present
       resource_group_name: "{{ CheckPointSMS | default('CheckPointGw', true) }}"
       template_link: 'https://raw.githubusercontent.com/cadgo/CHKP/master/azure/SMS.json'
       parameters:
         location:
           value: East US
         vmName:
           value: "{{ SMSName }}"
         adminPassword:
           value: "{{ Password }}"
         Subnet1StartAddress:
           value: 10.0.1.11
         vnetNewOrExisting:
           value: existing
         virtualNetworkExistingRGName:
           value: CheckPointGw
         
