FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirments.txt /code/
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y ansible
RUN pip3 install -r requirments.txt
RUN ansible-galaxy install azure.azure_modules
ADD . /code/
RUN /code/config.sh subscription_id client_id secret tenant
