---
  - name: Next ID
    uri:
      url: https://{{ prox_ip }}:{{ prox_port }}/api2/json/cluster/nextid
      method: GET
      status_code: 200
      validate_certs: False
      headers:
        Authorization: "{{apikey}}"
    register: nextid

  - name: Set Next ID
    set_fact:
      new_id: "{{nextid.json.data}}"

  - debug: msg="Free ID to Use {{new_id}}"
