---
- hosts: localhost                        # Note #2 in the Description section
  tasks:
  - name: login                           # You have to login to the management
                                            # server before running any commands
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"           # Variables set in /etc/ansible/hosts, to avoid needing
        password: "{{mgmt_password}}"       # to type your login details in every playbook.
        management: "{{mgmt_server}}"
      fingerprint: "42:E4:FA:36:19:AE:6E:F8:2A:78:53:A4:ED:2B:27:16:1F:A9:92:37"
    register: login_response                # Register the output from the login
          
  - name: "create-new-policy-package"
    check_point_mgmt:
      command: add-package
      parameters:
       name: "vsx3Package"
       comments: "created"
       color: "red"
       threat-prevention: "false"
       access: "true"
      session-data: "{{ login_response }}"
  
  - name: "vsx3_group_net"
    check_point_mgmt:
      command: add-group
      parameters:
       name: "vsx3_grp_intnet"
      session-data: "{{ login_response }}"

  - name: "vsx3_internal_net"
    check_point_mgmt:
      command: add-network
      parameters:
       name: "vsx3_int_net"
       subnet: "172.45.68.0"
       subnet-mask: "255.255.255.0"
       groups: "vsx3_grp_intnet"
      session-data: "{{ login_response }}"
      
  - name: "vsx3 host protected"
    check_point_mgmt:
      command: add-host
      parameters:
       name: "pc_172.45.68.20"
       ip-address: "172.45.68.20"
       nat-settings:
        auto-rule: "true"
        method: "static"
        ip-address: "192.168.100.100"
        install-on: "vsx3"     
      session-data: "{{ login_response }}"
  
  - name: "Seccion de entrada"
    check_point_mgmt:
      command: add-access-section
      parameters:
       name: "Reglas de entrada"
       layer: "vsx3Package Network"
       position: "top"
      session-data: "{{ login_response }}"
      
  # - name: "publish"
    # check_point_mgmt:
      # command: publish
      # session-data: "{{ login_response }}"

  - name: "Politica 1 de entrada"
    check_point_mgmt:
      command: add-access-rule
      parameters:
       layer: "vsx3Package Network"
       name: "Regla de Entrada a los servidores"
       position:
        top: "Reglas de entrada"
       source:
        - "any"
       destination:
        - "pc_172.45.68.20"
       service:
        - "any"
       action: "accept"
       track: "log"
      session-data: "{{ login_response }}"
      
  - name: "Seccion de salida"
    check_point_mgmt:
      command: add-access-section
      parameters:
       name: "Reglas de salida"
       layer: "vsx3Package Network"
       position: "2"
      session-data: "{{ login_response }}" 
  
  - name: "Politica 1 de Salida"
    check_point_mgmt:
      command: add-access-rule
      parameters:
       layer: "vsx3Package Network"
       name: "Regla de Entrada a los servidores"
       position:
        top: "Reglas de salida"
       source:
        - "vsx3_grp_intnet"
       destination:
        - "any"
       service:
        - "icmp-proto"
       action: "drop"
       track: "log"
      session-data: "{{ login_response }}"  
      
  # - name: "discard"
    # check_point_mgmt:
      # command: discard
      # session-data: "{{ login_response }}"
 
  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{ login_response }}"
      
  - name: "Install VSX3"
    check_point_mgmt:
      command: install-policy
      parameters:
       policy-package: "vsx3Package"
       targets: "vsx3"
      session-data: "{{ login_response }}"

