---
  - name: "Encoding Network LXC Configuration"
    set_fact:
      net: "net0={{nets|urlencode|replace('/','%2F')}}"

  - debug: msg="{{net}}"

  - name: "Creating an LXC {{new_id}}"
    uri: 
      url: "https://{{prox_ip}}:{{prox_port}}/api2/json/nodes/{{node}}/lxc?ostemplate={{ostemplate}}&vmid={{new_id}}&hostname={{hostname}}&cores={{cores}}&memory={{memory}}&swap={{swap}}&rootfs={{rootfs}}&nameserver={{nameserver}}&password={{lxc_password}}&{{net}}"
      method: POST
      validate_certs: False
      headers:
        Authorization: "{{apikey}}"
    register: instance_out

  - name: obtaining UPID
    set_fact: UPID="{{instance_out.json.data}}"

  - name: Monitoring LXC Creation
    uri:
      url: "https://{{prox_ip}}:{{prox_port}}/api2/json/nodes/{{node}}/tasks/{{UPID}}/status"
      method: GET
      status_code: 200
      validate_certs: False
      headers:
        Authorization: "{{apikey}}"
    register: Status
    until: Status.json.data.status == "stopped"
    retries: 10
    delay: 5
        
  - name: "Starting instance {{new_id}}"
    uri:
      url: "https://{{prox_ip}}:{{prox_port}}/api2/json/nodes/{{node}}/lxc/{{new_id}}/status/start"
      method: POST
      status_code: 200
      validate_certs: False
      headers:
        Authorization: "{{apikey}}"
