---
  - name: Proxmox Logging
    uri:
      url: https://{{ prox_ip }}:{{ prox_port }}/api2/json/access/ticket?username={{ user }}&password={{password}}
      method: POST
      status_code: 200
      validate_certs: False
    register: logging_info

  - name: obtaining tocken and ticket
    set_fact:
      token: "{{logging_info.json.data.CSRFPreventionToken}}"
      ticket: "{{logging_info.json.data.ticket}}"

  - name: Next ID
    uri:
      url: https://{{ prox_ip }}:{{ prox_port }}/api2/json/cluster/nextid
      method: GET
      status_code: 200
      validate_certs: False
      headers:
        CSRFPreventionToken: "{{token}}"
        Cookie: "PVEAuthCookie={{ticket}}"
    register: nextid

  - name: Set Next ID
    set_fact:
      new_id: "{{nextid.json.data}}"

  - debug: msg="Free ID to Use {{new_id}}"
