---
- hosts: localhost
  gather_facts: False
  vars_files: 
    - vault_password.yml
  tasks:
    - name: proxmox clone
      include_role: 
        name: prox_api
      vars:
        api_password: "{{ password }}"
        storage: evossd1

- hosts: chkp_prox
  gather_facts: False
  tasks:
    - name: Run FTW
      include_role: 
        name: if_ftw_config
      vars:
        vmname: Lab1
        install_gw: True
        eth0_real_ip: 192.168.100.67
