---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    - ansible_python_interpreter: "/usr/bin/python"
  vars_files: 
    - vault_password.yml
  roles:
    - role: vm_prox_clone
      vars:
        api_password: "{{ password }}" 
